### ISSUE TITLE
Test failure: `<"FooExt#a">` expected but was `<"Foo#a">`

### ISSUE THREAD

**Issue by wks** [mmtk/ruby#75]
The following error occured while running test-all with StickyImmix. See: https://github.com/mmtk/mmtk-ruby/actions/runs/9850740185/job/27196445111?pr=82

```
    1) Failure:
  TestRefinement#test_using_same_class_refinements [/home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:174]:
  <"FooExt#a"> expected but was
  <"Foo#a">.
  
    2) Failure:
  TestRefinement#test_module_inclusion2 [/home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:980]:
  <"FooExt2#x"> expected but was
  <"Foo#x">.
  
    3) Failure:
  TestRefinement#test_override [/home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:153]:
  <"FooExt#x"> expected but was
  <"Foo#x">.
  
    4) Failure:
  TestRefinement#test_module_using [/home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:906]:
  <"FooExt#x"> expected but was
  <"Foo#x">.
  
    5) Failure:
  TestRefinement#test_super_not_chained [/home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:167]:
  <"FooExt2#y Foo#y"> expected but was
  <"Foo#y">.
  
    6) Error:
  TestRefinement#test_new_method:
  NoMethodError: undefined method 'z' for an instance of TestRefinement::Foo
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:98:in 'TestRefinement::FooExtClient.invoke_z_on'
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:181:in 'TestRefinement#test_new_method'
  
    7) Error:
  TestRefinement#test_send_should_use_refinements:
  NoMethodError: undefined method 'z' for an instance of TestRefinement::Foo
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:102:in 'TestRefinement::FooExtClient.send_z_on'
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:205:in 'TestRefinement#test_send_should_use_refinements'
  
    8) Error:
  TestRefinement#test_method_should_use_refinements:
  NameError: undefined method 'z' for class 'TestRefinement::Foo'
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:118:in 'Kernel#method'
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:118:in 'TestRefinement::FooExtClient.method_z'
      /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/test/ruby/test_refinement.rb:232:in 'TestRefinement#test_method_should_use_refinements'
  
  Finished tests in 75.601716s, 116.2275 tests/s, 71205.8176 assertions/s.
  8787 tests, 5383282 assertions, 5 failures, 3 errors, 40 skips
  
  ruby -v: ruby 3.4.0dev (2024-07-08T17:55:17Z :detached: 7acf6a2eb5) +MMTk(StickyImmix) [x86_64-linux]
  make: *** [uncommon.mk:966: yes-test-all] Error 8
```

**Comment by wks** [comment]
This is likely caused by erroneously removing Hash objects from the list of PPPs.  The bug was introduced in https://github.com/mmtk/mmtk-ruby/pull/80 and it has been reverted.
